universe                = docker
docker_image            = maba00001/firsttry:latest
docker_pull_policy      = always
requirements            = (CUDACapability >= 8.6) && (CUDADriverVersion >= 12.6)
executable              = shell_gpu.sh
output                  = cluster.$(ClusterId).$(ProcId).out
error                   = cluster.$(ClusterId).$(ProcId).err
log                     = cluster.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
request_GPUs = 1
request_CPUs = 32
request_memory = 128G
+RequiresGPUAccess = true
+WantDocker = true
+WantGPULab = true
+RequiresNVIDIA = true
requirements = UidDomain == "cs.uni-saarland.de" 
getenv = HOME
+WantGPUHomeMounted = true
queue 10
